[package]
name = "hello_solana_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "2.2.3"
solana-program = "2.2.1"
solana-sdk = "2.2.1"
spl-token = "7.0.0"
spl-associated-token-account = "6.0.0"
borsh = "1.5.5"